server:
  port: 443
  ssl:
    key-store: classpath:keystore/app.p12
    key-store-password: pYDuYjnGMdCF3seAEJrN
    key-store-type: pkcs12
    key-alias: app
    key-password: pYDuYjnGMdCF3seAEJrN
  error:
    whitelabel:
      enabled: false
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: security
    password: JhCMLmaQubn6KjDVxN2dcFyreRvEXg
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 8f3368a90cd43d
    password: 1e377102580a85
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
seeders:
  enabled: true
