server:
  port: 80
  error:
    whitelabel:
      enabled: false
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: security
    password: JhCMLmaQubn6KjDVxN2dcFyreRvEXg
seeders:
  enabled: true
